apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: symbiote-cloudconfig
  name: symbiote-cloudconfig
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: symbiote-cloudconfig
  template:
    metadata:
      labels:
        io.kompose.network/symbioteL2: "true"
        io.kompose.service: symbiote-cloudconfig
    spec:
      initContainers:
        - name: init-myservice
          image: alpine/git:2.36.3
          command:
            - sh
            - -c
            - |
              cp /configmap/files/*  /tmp/configs/
              cd /tmp/configs/
              git init .
              git config user.email "admin@iotfeds.eu"
              git config user.name "iotfeds"
              git config --global --add safe.directory '*'
              git add .
              git commit -m "Initialize config files"
          volumeMounts:
            - name: tmp
              mountPath: /tmp/configs
            - mountPath: /configmap/files
              name: all-configmap-volume
      containers:
        - image: symbioteh2020/symbiote-cloudconfig:3.0.4
          name: symbiote-cloudconfig
          command:
            - sh
            - -c
            - |
              if [[ ! -e /home/CloudConfigProperties/.git ]]; then cp -a /tmp/configs/. /home/CloudConfigProperties; fi
              java -Xms128m -Xmx256m -XX:+UseContainerSupport -Duser.home=/home -jar $(ls *.jar)
          ports:
            - containerPort: 8888
          resources:
            limits:
              memory: "750M"
              cpu: "500m"
            requests:
              memory: "500M"
              cpu: "300m"
          volumeMounts:
            - name: tmp
              mountPath: /tmp/configs
            - mountPath: /home/CloudConfigProperties
              name: symbiote-vol-config
      restartPolicy: Always
      volumes:
        - name: tmp
          emptyDir: {}
        - name: symbiote-vol-config
          persistentVolumeClaim:
            claimName: symbiote-vol-config
        - name: all-configmap-volume
          configMap:
            name: all-config-maps