apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: symbiote-aam
  name: symbiote-aam
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: symbiote-aam
  template:
    metadata:
      labels:
        io.kompose.network/symbioteL2: "true"
        io.kompose.service: symbiote-aam
    spec:
      containers:
        - env:
            - name: holder
              value: ' '
          image: symbioteh2020/symbiote-aam:5.0.12
          name: symbiote-aam
          # command: ["sleep"]
          # args: ["100000"]
          command: ["/bin/sh","-c"]
          args: ["./configure.sh 27.5.0 && java -Xms128m -Xmx256m -XX:+UseContainerSupport -jar $(ls *run.jar)"]
          resources:
            limits:
              memory: "1000Mi"
              cpu: "1"
            requests:
              memory: "500Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /home/bootstrap.properties
              name: authenticationauthorizationmanager-bootstrap-configmap-volume
              subPath: bootstrap.properties
            - mountPath: /home/cert.properties
              name: authenticationauthorizationmanager-cert-configmap-volume
              subPath: cert.properties
      volumes:
        - name: authenticationauthorizationmanager-bootstrap-configmap-volume
          configMap:
            name: authenticationauthorizationmanager-bootstrap-configmap
        - name: authenticationauthorizationmanager-cert-configmap-volume
          configMap:
            name: authenticationauthorizationmanager-cert-configmap