apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: symbiote-rabbitmq
  name: symbiote-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: symbiote-rabbitmq
  template:
    metadata:
      labels:
        io.kompose.network/symbioteL2: "true"
        io.kompose.service: symbiote-rabbitmq
    spec:
      containers:
        - env:
            - name: holder
              value: ' '
          image: rabbitmq:3-alpine
          name: symbiote-rabbitmq
          ports:
            - containerPort: 5671
            - containerPort: 5672
          resources:
            limits:
              memory: "512M"
              cpu: "500m"
            requests:
              memory: "500M"
              cpu: "300m"
