apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: symbiote-rap
  name: symbiote-rap
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: symbiote-rap
  template:
    metadata:
      labels:
        io.kompose.network/symbioteL2: "true"
        io.kompose.service: symbiote-rap
    spec:
      containers:
        - env:
            - name: holder
              value: ' '
          image: iotfedsproject/rap:0.1.0
          name: symbiote-rap
          command: ["/bin/sh","-c"]
          args: ["java -Xms128m -Xmx256m -XX:+UseContainerSupport -DSPRING_BOOT_WAIT_FOR_SERVICES=symbiote-aam:8080 -jar $(ls *run.jar)"]
          resources:
            limits:
              memory: "750Mi"
              cpu: "1"
            requests:
              memory: "500Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /home/application.properties
              name: rappluginstarter-application-configmap-volume
              subPath: application.properties
      volumes:
        - name: rappluginstarter-application-configmap-volume
          configMap:
            name: rappluginstarter-application-configmap