apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: symbiote-mongo
  name: symbiote-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: symbiote-mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/symbioteL2: "true"
        io.kompose.service: symbiote-mongo
    spec:
      containers:
        - image: mongo:3.6
          name: symbiote-mongo
          resources:
            limits:
              memory: "512M"
              cpu: "500m"
            requests:
              memory: "256M"
              cpu: "300m"
          volumeMounts:
            - mountPath: /data/db
              name: symbiote-vol
      restartPolicy: Always
      volumes:
        - name: symbiote-vol
          persistentVolumeClaim:
            claimName: symbiote-vol

