apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: symbiote-core-vol
  name: symbiote-core-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
status: {}
