apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    icom.symbiote.service: symbiote-coreconfig
  name: symbiote-coreconfig
spec:
  replicas: 1
  selector:
    matchLabels:
      icom.symbiote.service: symbiote-coreconfig
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        icom.symbiote.service: symbiote-coreconfig
    spec:
      initContainers:
        - name: init-myservice
          image: alpine/git:2.36.3
          command:
          - sh
          - -c
          - |
            cp /configmap/files/*  /tmp/configs/
            cd /tmp/configs/
            git init .
            git config user.email "admin@iotfeds.eu"
            git config user.name "iotfeds"
            git config --global --add safe.directory '*'
            git add .
            git commit -m "Initialize config files" 
          volumeMounts:
            - name: tmp
              mountPath: /tmp/configs
            - mountPath: /configmap/files
              name: all-configmap-volume
      containers:
        - image: symbioteh2020/symbiote-coreconfig:3.0.5
          name: symbiote-coreconfig
          command:
          - sh
          - -c
          - |
            if $ALWAYS_UPDATE; then rm -rf /home/CoreConfigProperties/.git; fi
            if [[ ! -e /home/CoreConfigProperties/.git ]]; then cp -a /tmp/configs/. /home/CoreConfigProperties; fi
            java -Xms128m -Xmx256m -XX:+UseContainerSupport -DSPRING_BOOT_WAIT_FOR_SERVICES=symbiote-aam:8080 -Duser.home=/home -jar $(ls *.jar)
          env:
            - name: ALWAYS_UPDATE
              value: "true"
          resources:
            limits:
              memory: "300Mi"
              cpu: "400m"
            requests:
              memory: "200Mi"
              cpu: "200m"
          ports:
            - containerPort: 8888
          volumeMounts:
            - name: tmp
              mountPath: /tmp/configs
            - mountPath: /home/CoreConfigProperties
              name: symbiote-vol-config
      volumes:
        - name: tmp
          emptyDir: {}
        - name: symbiote-vol-config
          persistentVolumeClaim:
            claimName: symbiote-vol-config
        - name: all-configmap-volume
          configMap:
            name: all-config-maps