apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    icom.symbiote.service: symbiote-rabbitmq
  name: symbiote-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      icom.symbiote.service: symbiote-rabbitmq
  template:
    metadata:
      labels:
        icom.symbiote.network/symbiote: "true"
        icom.symbiote.service: symbiote-rabbitmq
    spec:
      containers:
        - image: rabbitmq:3-management
          name: symbiote-rabbitmq
          ports:
            - containerPort: 5671
            - containerPort: 5672
          resources:
            limits:
              memory: "300Mi"
              cpu: "500m"
            requests:
              memory: "200Mi"
              cpu: "200m"
