apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: symbiote-registry
  name: symbiote-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      icom.symbiote.service: symbiote-registry
  template:
    metadata:
      labels:
        icom.symbiote.service: symbiote-registry
    spec:
      containers:
        - image: symbioteh2020/symbiote-registry:3.0.4
          name: symbiote-registry
          command: ["/bin/sh","-c"]
          args: ["java -Xms128m -Xmx256m -XX:+UseContainerSupport -DSPRING_BOOT_WAIT_FOR_SERVICES=symbiote-coreinterface:8100 -Duser.home=/home -jar $(ls *.jar)"]
          resources:
            limits:
              memory: "750Mi"
              cpu: "750m"
            requests:
              memory: "500Mi"
              cpu: "400m"
          volumeMounts:
            - mountPath: /home/bootstrap.properties
              name: bootstrap-properties-configmap-volume
              subPath: bootstrap.properties
      volumes:
        - name: bootstrap-properties-configmap-volume
          configMap:
              name: bootstrap-properties-configmap
