namespaceOverride: "monitoring"

alertmanager:
  enabled: false

grafana:
  grafana.ini:
    date_formats:
      full_date = YYYY-MM-DD HH:mm:ss
      interval_second = HH:mm:ss
      interval_minute = HH:mm
      interval_hour = DD/MM HH:mm
      interval_day = DD/MM
      interval_month = YYYY-MM
      interval_year = YYYY

prometheusOperator:
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 100Mi
        
prometheus:
  prometheusSpec:
    retention: 10d
    replicas: 1

    resources: 
      requests:
        memory: 400Mi
      limits:
        memory: 600Mi

    storageSpec: 
     volumeClaimTemplate:
       spec:
         accessModes: ["ReadWriteOnce"]
         resources:
           requests:
             storage: 5Gi
