{{- if and .Values.server.enabled .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudcoreinterface-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.ingressClassName }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header 'Content-Security-Policy' 'upgrade-insecure-requests';
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: symbiote-cloudcoreinterface
                port:
                  number: 8101
{{- end -}}