apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: symbiote-sm
  name: symbiote-sm
spec:
  ports:
    - name: "8128"
      port: 8128
      targetPort: 8128
  selector:
    io.kompose.service: symbiote-sm
