apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: symbiote-rap
  name: symbiote-rap
spec:
  ports:
    - name: "8103"
      port: 8103
      targetPort: 8103
  selector:
    io.kompose.service: symbiote-rap
