apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: symbiote-cloudconfig
  name: symbiote-cloudconfig
spec:
  ports:
    - name: "8888"
      port: 8888
      targetPort: 8888
  selector:
    io.kompose.service: symbiote-cloudconfig