server:
  enabled: true

image:
  repository: symbioteh2020/symbiote-cram
  tag: "3.0.6"
  pullPolicy: IfNotPresent

# resources: {}
resources:
  limits:
    memory: "750Mi"
    cpu: "1"
  requests:
    memory: "500Mi"
    cpu: "500m"
