apiVersion: v1
kind: Service
metadata:
  labels:
    icom.symbiote.service: symbiote-eureka
  name: symbiote-eureka
spec:
  ports:
    - name: "8761"
      port: 8761
      targetPort: 8761
  selector:
    icom.symbiote.service: symbiote-eureka
