apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    icom.symbiote.service: symbiote-semanticmanager
  name: symbiote-semanticmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      icom.symbiote.service: symbiote-semanticmanager
  template:
    metadata:
      labels:
        icom.symbiote.service: symbiote-semanticmanager
    spec:
      containers:
        - image: symbioteh2020/symbiote-semanticmanager:3.0.3
          name: symbiote-semanticmanager
          command: ["/bin/sh","-c"]
          args: ["java -Xms128m -Xmx256m -XX:+UseContainerSupport -Duser.home=/home -DSPRING_BOOT_WAIT_FOR_SERVICES=symbiote-coreinterface:8100 -jar $(ls *.jar)"]
          resources:
            limits:
              memory: "750Mi"
              cpu: "1"
            requests:
              memory: "500Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /home/bootstrap.properties
              name: bootstrap-properties-configmap-volume
              subPath: bootstrap.properties
      volumes:
        - name: bootstrap-properties-configmap-volume
          configMap:
              name: bootstrap-properties-configmap
