apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    icom.symbiote.service: symbiote-mongo
  name: symbiote-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      icom.symbiote.service: symbiote-mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        icom.symbiote.service: symbiote-mongo
    spec:
      containers:
        - image: mongo:3.6
          name: symbiote-mongo
          ports:
            - containerPort: 27017
          resources:
            limits:
              memory: "300Mi"
              cpu: "500m"
            requests:
              memory: "200Mi"
              cpu: "100m"
          volumeMounts:
            - mountPath: /data/db
              name: symbiote-core-vol
      volumes:
        - name: symbiote-core-vol
          persistentVolumeClaim:
            claimName: symbiote-core-vol